import io
import os
import numpy as np
import pandas as pd
from datetime import datetime
from typing import Dict, Any, List

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, PageBreak
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.pdfgen import canvas
    HAS_REPORTLAB = True
    CanvasBase = canvas.Canvas
except ImportError:
    HAS_REPORTLAB = False
    CanvasBase = object

class NumberedCanvas(CanvasBase):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 755, "ForecastAI — Time-Series Forecasting Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 747, 558, 747)

        # Footer
        text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, text)
        self.drawString(54, 36, "Generated by ForecastAI Platform • Confidential & Proprietary")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        self.restoreState()


def render_forecast_chart_to_buffer(
    historical_dates: List[str],
    historical_values: List[float],
    forecast_dates: List[str],
    forecast_values: List[float],
    lower_ci: List[float],
    upper_ci: List[float],
    order_str: str
) -> io.BytesIO:
    # Modern dark/clean plotting style
    plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
    fig, ax = plt.subplots(figsize=(8.5, 3.8), dpi=200)

    # Convert to timestamps for proper continuous x-axis
    hist_dt = pd.to_datetime(historical_dates)
    fc_dt = pd.to_datetime(forecast_dates)

    # Plot historical line
    # Sample if historical is very dense for clarity
    sample_rate = max(1, len(hist_dt) // 150)
    ax.plot(hist_dt[::sample_rate], [historical_values[i] for i in range(0, len(historical_values), sample_rate)],
            color="#2563EB", linewidth=1.8, label="Historical Actuals", alpha=0.9)

    # Connect last historical point to forecast
    all_fc_dt = [hist_dt[-1]] + list(fc_dt)
    all_fc_val = [historical_values[-1]] + list(forecast_values)
    all_low = [historical_values[-1]] + list(lower_ci)
    all_up = [historical_values[-1]] + list(upper_ci)

    # Plot forecast trajectory
    ax.plot(all_fc_dt, all_fc_val, color="#10B981", linewidth=2.2, linestyle="--", label=f"Forecast ({order_str})")

    # Plot confidence band
    ax.fill_between(all_fc_dt, all_low, all_up, color="#10B981", alpha=0.18, label="95% Confidence Interval")

    # Separation vertical line
    ax.axvline(hist_dt[-1], color="#94A3B8", linestyle=":", linewidth=1.2, alpha=0.8)
    ax.text(hist_dt[-1], ax.get_ylim()[1] * 0.96, " Forecast Start ", color="#475569",
            fontsize=8, ha="right", va="top", backgroundcolor="white")

    ax.set_title(f"ARIMA Time-Series Projection ({order_str})", fontsize=11, fontweight="bold", pad=10, color="#1E293B")
    ax.set_xlabel("Timeline", fontsize=9, color="#475569")
    ax.set_ylabel("Value", fontsize=9, color="#475569")
    ax.tick_params(axis='both', which='major', labelsize=8)
    ax.legend(loc="upper left", frameon=True, facecolor="#F8FAFC", edgecolor="#E2E8F0", fontsize=8)

    plt.tight_layout()
    buf = io.BytesIO()
    plt.savefig(buf, format="png", bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def generate_pdf_report(
    filename: str,
    dataset_name: str,
    date_col: str,
    target_col: str,
    row_count: int,
    frequency: str,
    stationarity_info: Dict[str, Any],
    model_order_str: str,
    metrics: Dict[str, Any],
    forecast_table: List[Dict[str, Any]],
    historical_points: List[Dict[str, Any]],
    diagnostics: Dict[str, Any]
) -> bytes:
    if not HAS_REPORTLAB or not HAS_MATPLOTLIB:
        raise RuntimeError("PDF export requires 'reportlab' and 'matplotlib'. Use CSV export instead or install these libraries.")
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#0F172A')
    )

    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#2563EB')
    )

    h2_style = ParagraphStyle(
        'Heading2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=14,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#334155')
    )

    meta_label = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#475569')
    )

    meta_val = ParagraphStyle(
        'MetaVal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#0F172A')
    )

    story = []

    # Header / Title banner
    story.append(Paragraph("ForecastAI", subtitle_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph("Time-Series Prediction & Model Report", title_style))
    story.append(Spacer(1, 4))
    gen_time = datetime.now().strftime('%B %d, %Y • %H:%M UTC')
    story.append(Paragraph(f"Generated on {gen_time} for dataset <b>{dataset_name}</b>", body_style))
    story.append(Spacer(1, 14))

    # Divider line
    divider = Table([[""]], colWidths=[504], rowHeights=[2])
    divider.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#3B82F6')),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(divider)
    story.append(Spacer(1, 14))

    # Section 1: Executive Overview & Dataset
    story.append(Paragraph("1. Dataset & Series Profile", h2_style))
    
    meta_table_data = [
        [
            Paragraph("Dataset File:", meta_label), Paragraph(dataset_name, meta_val),
            Paragraph("Total Observations:", meta_label), Paragraph(f"{row_count:,}", meta_val),
        ],
        [
            Paragraph("Date Column:", meta_label), Paragraph(date_col, meta_val),
            Paragraph("Series Frequency:", meta_label), Paragraph(frequency, meta_val),
        ],
        [
            Paragraph("Target Metric:", meta_label), Paragraph(target_col, meta_val),
            Paragraph("Model Specification:", meta_label), Paragraph(model_order_str, meta_val),
        ]
    ]

    t_meta = Table(meta_table_data, colWidths=[110, 142, 110, 142])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 12))

    # Section 2: Stationarity & Statistical Properties
    story.append(Paragraph("2. Stationarity Assessment (Augmented Dickey-Fuller Test)", h2_style))
    adf_stat = stationarity_info.get("adf_statistic", 0.0)
    p_val = stationarity_info.get("p_value", 1.0)
    is_stat = stationarity_info.get("is_stationary", False)
    verdict_text = "Stationary (Reject H0)" if is_stat else "Non-Stationary (Unit Root Present)"
    verdict_color = colors.HexColor("#10B981") if is_stat else colors.HexColor("#F59E0B")

    stat_data = [
        [
            Paragraph("ADF Test Statistic", meta_label),
            Paragraph(f"{adf_stat:.4f}", meta_val),
            Paragraph("p-value", meta_label),
            Paragraph(f"{p_val:.4f}", meta_val),
            Paragraph("Verdict", meta_label),
            Paragraph(f"<b>{verdict_text}</b>", ParagraphStyle('V', parent=meta_val, textColor=verdict_color))
        ]
    ]
    t_stat = Table(stat_data, colWidths=[90, 70, 60, 60, 60, 164])
    t_stat.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F1F5F9')),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_stat)
    story.append(Spacer(1, 6))
    story.append(Paragraph(stationarity_info.get("interpretation", ""), body_style))
    story.append(Spacer(1, 12))

    # Section 3: Model Evaluation Metrics
    story.append(Paragraph("3. Model Validation & Performance Metrics", h2_style))
    mae = metrics.get("mae", 0.0)
    rmse = metrics.get("rmse", 0.0)
    mape = metrics.get("mape", 0.0)
    aic = metrics.get("aic", 0.0)
    bic = metrics.get("bic", 0.0)

    perf_data = [
        ["Metric", "Value", "Description"],
        ["MAE (Mean Absolute Error)", f"{mae:.2f}", "Average absolute difference between predictions and actual holdout values."],
        ["RMSE (Root Mean Squared Error)", f"{rmse:.2f}", "Penalizes larger forecast errors more heavily."],
        ["MAPE (Mean Absolute % Error)", f"{mape:.2f}%", "Percentage error relative to actual magnitude."],
        ["AIC (Akaike Info Criterion)", f"{aic:.2f}", "Relative model quality balance between fit and complexity."],
        ["BIC (Bayesian Info Criterion)", f"{bic:.2f}", "Criterion with stronger penalty for number of parameters."]
    ]
    t_perf = Table(perf_data, colWidths=[150, 80, 274])
    t_perf.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8.5),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0,0), (-1,-1), 4.5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4.5),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_perf)
    story.append(Spacer(1, 14))

    # Section 4: Visual Forecast Chart
    story.append(Paragraph("4. Time-Series Historical & Future Trajectory", h2_style))
    try:
        hist_dates = [p["date"] for p in historical_points]
        hist_vals = [p["value"] for p in historical_points]
        fc_dates = [f["date"] for f in forecast_table]
        fc_vals = [f["predicted"] for f in forecast_table]
        low_ci = [f["lower_ci"] for f in forecast_table]
        up_ci = [f["upper_ci"] for f in forecast_table]

        chart_buf = render_forecast_chart_to_buffer(
            hist_dates, hist_vals, fc_dates, fc_vals, low_ci, up_ci, model_order_str
        )
        img = Image(chart_buf, width=504, height=225)
        story.append(img)
    except Exception as e:
        story.append(Paragraph(f"Chart rendering note: {str(e)}", body_style))
    story.append(Spacer(1, 14))

    # Page Break for clean table and diagnostics
    story.append(PageBreak())

    # Section 5: Future Predictions Table (Sample of upcoming horizon)
    story.append(Paragraph("5. Forecast Schedule & Confidence Intervals (95%)", h2_style))
    story.append(Paragraph(
        "Below are projected values along with the lower and upper bounds of the 95% statistical confidence envelope.",
        body_style
    ))
    story.append(Spacer(1, 8))

    fc_headers = ["Period / Date", "Predicted Value", "95% Lower Bound", "95% Upper Bound"]
    fc_rows = [fc_headers]
    
    # Take up to first 25 rows for concise professional presentation
    preview_rows = forecast_table[:25]
    for r in preview_rows:
        fc_rows.append([
            str(r["date"]),
            f"{r['predicted']:.2f}",
            f"{r['lower_ci']:.2f}",
            f"{r['upper_ci']:.2f}"
        ])

    t_fc = Table(fc_rows, colWidths=[126, 126, 126, 126])
    t_fc.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8.5),
        ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_fc)
    
    if len(forecast_table) > 25:
        story.append(Spacer(1, 4))
        story.append(Paragraph(f"<i>Showing first 25 of {len(forecast_table)} forecast periods. Full schedule available in CSV export.</i>", body_style))
    story.append(Spacer(1, 14))

    # Section 6: Model Diagnostics & Residual Analysis
    story.append(Paragraph("6. Residual Diagnostics & Goodness-of-Fit", h2_style))
    lb_stat = diagnostics.get("ljung_box_stat", 0.0)
    lb_p = diagnostics.get("ljung_box_p_value", 1.0)
    is_wn = diagnostics.get("is_white_noise", True)
    diag_interp = diagnostics.get("interpretation", "")

    diag_data = [
        [
            Paragraph("Ljung-Box Statistic:", meta_label), Paragraph(f"{lb_stat:.3f}", meta_val),
            Paragraph("p-value:", meta_label), Paragraph(f"{lb_p:.4f}", meta_val),
            Paragraph("White Noise Status:", meta_label),
            Paragraph("Passed (White Noise)" if is_wn else "Check Autocorrelation",
                      ParagraphStyle('WN', parent=meta_val, textColor=colors.HexColor("#10B981") if is_wn else colors.HexColor("#EF4444")))
        ]
    ]
    t_diag = Table(diag_data, colWidths=[105, 60, 60, 60, 95, 124])
    t_diag.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F1F5F9')),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_diag)
    story.append(Spacer(1, 6))
    story.append(Paragraph(diag_interp, body_style))
    story.append(Spacer(1, 14))

    # Section 7: Conclusion & Strategic Takeaways
    story.append(Paragraph("7. Strategic Conclusions & Operational Next Steps", h2_style))
    conclusion_text = (
        f"The configured <b>{model_order_str}</b> model successfully captured the underlying structure of "
        f"<b>{target_col}</b> across {row_count:,} observations. The estimated MAPE of {mape:.2f}% provides "
        "a reliable confidence baseline for resource planning, inventory stocking, and capacity management. "
        "Forecasts should be re-calibrated periodically as new observed data points become available."
    )
    story.append(Paragraph(conclusion_text, body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
